### ISSUE TITLE
Migrate from Google Universal Analytics to Google Analytics 4

### ISSUE THREAD

**Issue by jcscottiii** [web-platform-tests/wpt.fyi#2916]
# Current state of the Analytics System

Currently, we leverage Universal Analytics which is due for [deprecation](https://support.google.com/analytics/answer/11583528) in favor of Google Analytics 4. There is a [guide](https://support.google.com/analytics/answer/9304153#add-tag&zippy=%2Cadd-your-tag-using-google-tag-manager%2Cadd-the-global-site-tag-directly-to-your-web-pages) of how to migrate to Google Analytics which involes making changes to the existing gtag.js script. However, our implemenation of Universal Analytics uses analytics.js. Analytics.js is a dated version of  and should migrate to gtag.js before migrating directly to Google Analytics. This [document](https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs) demonstrates the migration path and differences.

# Detailed Plan

- [x] 1. Migrate existing analytics.js script to gtag.js for Universal Analytics. #2917 
  - [x] Switch to using tracking code that uses gtag.js
  - [x] Change all custom events that use `window.ga` or `ga` to `window.gtag` or `gtag`
  - Notes:
    - No longer need to [explicitly](https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs#measure_pageviews_with_the_default_tracker) send page view events in gtag.js
    - Events have a different format [(1)](https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs#measure_events) [(2)](https://developers.google.com/analytics/devguides/collection/gtagjs/events#default-event-categories-and-labels)
    - Exceptions have a different [format](https://developers.google.com/analytics/devguides/collection/gtagjs/exceptions) in terms of the exception parameters.
- [x] 2. Add additional configs to send information to the new Google Analytics 4 properties while also sending data to the existing Universal Analytics property. #2917 
  - Might be advantageous to setup Google Tag Manager to manage environments automatically later on. #2919 
- [ ] 3. Once confimed that everything works, remove the old Universal Analytics tracking code and keep only the Google Analytics tracking. #2921 

cc: @past @DanielRyanSmith @KyleJu

**Comment by jcscottiii** [comment]
After #2927 happened. It was confirmed that the Google Aanlytics 4 wptdashboard is now populating.

**Comment by past** [comment]
@jcscottiii do you have any theory as to why the two dashboards show different usage? Just looking at "all users" I see significant differences between the two charts.

![image](https://user-images.githubusercontent.com/49118/188987013-a487b819-e55d-4e47-a4f3-0723ea4bae55.png)

![image](https://user-images.githubusercontent.com/49118/188987165-af442a02-4351-4a0a-8fa4-fd884afed91b.png)

**Comment by jcscottiii** [comment]
For the universal analytics, by default it includes all traffic to any deployment of wpt.fyi (localhost, staging, prod, any custom deployments)
I created a custom segment to filter only on production (https://wpt.fyi) traffic. Here's how to use it.
1. Click on the "All Users" segment.
  - ![image](https://user-images.githubusercontent.com/7788930/189143317-c0834913-00b9-4e89-8181-29eb702a3401.png)
2. Uncheck All Users
3. Go to Custom and check WPT.FYI Prod
  - ![image](https://user-images.githubusercontent.com/7788930/189143606-e55e856e-3dcd-481a-b214-54b2d94f79d8.png)

With that comparison you'll get:

| Service  | Screenshot |
| ---------- | --------------- |
| Google Analytics 4 | ![image](https://user-images.githubusercontent.com/7788930/189150565-d7b6f3be-6ae3-4c43-a89f-2f20bf14094d.png) |
| Universal Analytics | ![image](https://user-images.githubusercontent.com/7788930/189150739-2cb028c4-a5de-4a83-8bc0-ea11033e3440.png) |

There's a 6% difference when focusing only on the traffic to wpt.fyi in Universal Analytics

I did some digging and found this [article](https://support.google.com/analytics/answer/11986666?hl=en#users&zippy=%2Cin-this-article). Summarized it says:
There is also a slight difference in the usage of "Users" between the Google Analytics 4 and Universal Analytics
- In Universal Analytics, "Users" means what you expect "Total Users"
- In Google Analytics 4, "Users" means "Active Users"

"Active Users" is measured by:
> any user who has an [engaged session](https://support.google.com/analytics/answer/9143382#engaged-sessions) or when Analytics collects the [first_visit](https://support.google.com/analytics/answer/9234069#first_visit) event or [engagement_time_msec](https://support.google.com/analytics/answer/9234069) parameter from a website`

Now I am looking into the 6% difference. "Active Users" have to be engaging the page in some way to be counted. So my initial hypothesis is that part of that 6% difference is from users that do not do anything on the page. I started diving into this using the DebugView in Google Analytics

I did look at the Page Views metrics. There are some major differences there.

| Service  | Screenshot |
| ---------- | --------------- |
| Google Analytics 4 | ![image](https://user-images.githubusercontent.com/7788930/189150565-d7b6f3be-6ae3-4c43-a89f-2f20bf14094d.png) |
| Universal Analytics | ![image](https://user-images.githubusercontent.com/7788930/189183016-11f681b8-0ead-45cf-9e38-213bc542c281.png) |

This one will take some more time to look into

**Comment by past** [comment]
This looks much more reassuring, thank you! In the [link](https://support.google.com/analytics/answer/11986666?hl=en#users&zippy=%2Cin-this-article) you shared I see this helpful paragraph:

> You can compare Total Users from UA to Total Users in GA4 by using [Explorations](https://support.google.com/analytics/answer/7579450) in GA4 to find your total users number. These numbers may be more comparable than the Users metrics in the GA4 reports due to the differences in definitions.

I created an exploration that showed a slightly elevated number of total users, although it didn't fully explain the 6% difference. By the way I couldn't find the WPT.FYI Prod segment in UA, maybe it needs to be shared first?

Anyway, I don't think the absolute values matter as much as the graph shape, which seems to be more or less consistent between the two after your production segmentation. Modulo your investigation uncovering any further discrepancies, I now feel much more confident about the collected data.

**Comment by jcscottiii** [comment]
Here's the segment: https://analytics.google.com/analytics/web/template?uid=TRn3Ezh2Sj6phuBlI2DlQw
(Can only share by link or put it publicly in the Solutions Gallery)
![image](https://user-images.githubusercontent.com/7788930/189383806-6d499343-168b-40fe-a939-db8b8d70c5bf.png)

I like your comment about the shape of the graph. It makes sense. Given that Google Analytics calculates things differently, it is a good point to keep in mind.

I will update the thread on the pageview. I did some debugging this morning. Will post my findings soon.

**Comment by jcscottiii** [comment]
Did some initial investigation. Seems like Google Analytics 4 right now is counting redirects as page views. This can lead to two views for a particular page (e.g Scenario 1). However, there are cases with the old Universal Analytics which are not counting some page views, thus missing data. (Scenarios 13 & 14)

Conclusion:
I feel more confident that Google analytics 4 is better and if we needed to cut over today, I would be 100% okay with it since it is capturing all the data whereas Universal Analytics is missing page view counts. The only problem with Google Analytics 4 is the duplicate page views from redirects (but that is not a deal breaker unlike missing data). I will look into how to stop duplicate data from the redirects.

Raw Notes below:
| Scenario      | Google Analytics 4 (new) | Universal Analytics (old)
| ----------- | ----------- | ----------- |
| Scenario 1. Going to the home page      | counts as two page_views. https://wpt.fyi redirects to these two page_view events: <br><ul><li>Location: https://wpt.fyi/results/ Referrer: None <li> Location: https://wpt.fyi/results/?label=experimental&label=master&aligned Referrer: https://wpt.fyi/results/</ul>     |      counts as one  pageview event<br><ul><li>https://wpt.fyi/results/</ul>      |
| Scenario 2. Clicking on "Latest Run" from the homepage      | Same as scenario 1       |      Same as scenario 1      |
| Scenario 3. Changing the channel on the homepage between stable and experimental      | Does nothing. As expected      |      Does nothing. As expected      |
| Scenario 4. Clicking on "accelerometer" from the homepage to go to the accelerometer page    | counts as one page_view <br><ul><li>Location: https://wpt.fyi/results/accelerometer?label=experimental&label=master&aligned Referrer: https://wpt.fyi/results/?label=experimental&label=master&aligned</ul>     |      counts as zero page views **BAD**  ❌    |
| Scenario 5. Clicking on "Accelerometer_insecure_context.html" from the accelerometer page    | counts as one page_view.  <br><ul><li>Location: https://wpt.fyi/results/accelerometer/Accelerometer_insecure_context.html?label=experimental&label=master&aligned Referrer: https://wpt.fyi/results/accelerometer?label=experimental&label=master&aligned</ul>     |      counts as zero page views **BAD**  ❌   |
| Scenario 6. Clicking the "Link" button and all the options   |    no page_view events. as expected since the page doesn't change  |      no page_view events. as expected since the page doesn't change   |
| Scenario 7. In the edit panel, Removing a product and clicking a submit. In this case, I removed safari.  |    counts as one page_view. <br><ul><li>Location: https://wpt.fyi/results/accelerometer/Accelerometer_insecure_context.html?label=master&label=experimental&product=chrome&product=edge&product=firefox&aligned&view=subtest Referrer: https://wpt.fyi/results/accelerometer/Accelerometer_insecure_context.html?label=experimental&label=master&aligned</ul>  |   counts as zero page views **BAD**  ❌       |
| Scenario 8. Clicking "Show History"  on a test page   |   does nothing as expected.   |         |
| Scenario 9. Clicking on a link that leaves the webapp (e.g. github)  |  yields no page_view events. That is expected    |   yields no pageview events. That is expected       |
| Scenario 10. Clicking "Recent runs"  in the top nav from scenario 9 page   |   counts as two page_views events <br><ul><li>Location: https://wpt.fyi/runs Referrer: https://wpt.fyi/results/accelerometer/Accelerometer_insecure_context.html?label=master&label=experimental&product=chrome&product=edge&product=firefox&aligned&view=subtest <li> Location: https://wpt.fyi/runs?label=master&from=2022-09-02T00%3A00&view=subtest Referrer: https://wpt.fyi/runs </ul>   |    counts as one  pageview event<br><ul><li>https://wpt.fyi/runs</ul>     |
| Scenario 11. Clicking on a SHA from the recent runs page   |  counts as two page_views events <br><ul><li>Location: https://wpt.fyi/results/?label=master&sha=09f51f2cf4&max-count=1 Referrer: https://wpt.fyi/runs?label=master&from=2022-09-02T00%3A00&view=subtest <li> Location: https://wpt.fyi/results/?sha=09f51f2cf4&label=master&max-count=1 Referrer: https://wpt.fyi/results/?label=master&sha=09f51f2cf4&max-count=1 </ul>    |    counts as one  pageview event<br><ul><li>https://wpt.fyi/results/?label=master&sha=09f51f2cf4&max-count=1</ul>     |
| Scenario 12. From the SHA page, click on the sha for a particular product.  |      |         |
| Scenario 13. From the SHA page, clicking on accelerometer category    |    counts as one page_view. <br><ul><li>Location: https://wpt.fyi/results/accelerometer?sha=09f51f2cf4&label=master&max-count=1 Referrer: https://wpt.fyi/results/?sha=09f51f2cf4&label=master&max-count=1</ul>  |   counts as zero page views **BAD**  ❌       |
| Scenario 14. From the SHA accelerometer page, clicking "Accelerometer_insecure_context.html"    |    counts as one page_view. <br><ul><li>Location: https://wpt.fyi/results/accelerometer/Accelerometer_insecure_context.html?sha=09f51f2cf4&label=master&max-count=1 Referrer: https://wpt.fyi/results/accelerometer?sha=09f51f2cf4&label=master&max-count=1</ul>  |   counts as zero page views **BAD**  ❌       |
| Scenario 15. From the recent runs page clicking on a particular product, then click view run   |    counts as two page_views events <br><ul><li>Location: https://wpt.fyi/results/?run_id=5100667390656512 Referrer: https://wpt.fyi/runs?label=master&from=2022-09-02T00%3A00&view=subtest <li> Location: https://wpt.fyi/results/?run_id=5100667390656512&view=subtest Referrer: https://wpt.fyi/results/?run_id=5100667390656512</ul>  |   counts as one pageview event    <br><ul><li>Location: https://wpt.fyi/results/?run_id=5100667390656512 </ul>     |
| Scenario 16. Clicking on Interop 2022 in top nav   |    counts as one page_views event <br><ul><li>Location: https://wpt.fyi/interop-2022 Referrer: https://wpt.fyi/results/?run_id=5100667390656512&view=subtest </ul>  |   counts as one pageview event    <br><ul><li>Location: https://wpt.fyi/interop-2022 </ul>     |
| Scenario 17. On the interop 2022 page, switching from experimental to stable  |    counts as one page_views event <br><ul><li>Location: https://wpt.fyi/interop-2022?stable Referrer: https://wpt.fyi/interop-2022 </ul>  |   counts as zero pageview events       |
| Scenario 18. On the interop 2022 page, switching back to experimental from stable    |    counts as one page_views event <br><ul><li>Location: https://wpt.fyi/interop-2022 Referrer: https://wpt.fyi/interop-2022?stable </ul>  |   counts as zero pageview events       |
| Scenario 19. On the interop 2022 page, clicking on the Cascade Layers category of tests    |    counts as one page_views event <br><ul><li>Location: https://wpt.fyi/results/css/css-cascade?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-cascadeReferrer: https://wpt.fyi/interop-2022 </ul>  |   counts as one pageview event    <br><ul><li>Location: https://wpt.fyi/results/css/css-cascade?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-cascade </ul>     |
| Scenario 20. Clicking on Insights in top nav   |    counts as one page_views event <br><ul><li>Location: https://wpt.fyi/insights </ul>  |   counts as one pageview event    <br><ul><li>Location: https://wpt.fyi/insights </ul>     |

**Comment by past** [comment]
Excellent write-up! I also feel comfortable with the migration now after this very thorough analysis.

**Comment by jcscottiii** [comment]
I did some more analysis into the scenarios where it counts as two events. (1 redirect and 1 actual destination with the added query parameters)

Google Analytics 4 is acting as intended.  I will move my PR from draft to ready.

## Conclusion (tl;dr the details below)
The collection of the 2 page_event events (1 for the redirect and 1 for the final rendered page) paints a picture of two types of users: Users that just go to the default page vs users that know the query string parameters and navigate directly with all the query string parameters. By trying to remove one or deduplicate these, you would lose the ability to discover this trend.


<details>
  <summary>More details below</summary>


## Looking at the data
Keeping as-is allows us to see which users come to the page without any query parameters vs those that come with a full url with query parameters. 


Creating a view to show query string parameter breakdown does not come by default. Following these [directions](https://www.analyticsmania.com/post/exclude-url-query-parameters-in-google-analytics-4/), I was able to see the breakdown.

![image](https://user-images.githubusercontent.com/7788930/189953561-95d26bc5-0a31-4517-8523-a23533e40b33.png)

**This difference is big enough to keep both events.**

(I also modified the shared [report](https://analytics.google.com/analytics/web/#/p152994087/reports/explorer?params=_u..nav%3Dmaui&r=4060819854&ruid=all-pages-and-screens,life-cycle,engagement&collectionId=life-cycle) for everyone to see by query string parameters)


## Debug

I also did a debug session by placing a breakpoint [here](https://github.com/web-platform-tests/wpt.fyi/blob/b2c1d3f82e80eda5cecc8609ee7ed4108a530f2d/webapp/components/test-runs-query.js#L113) and using the Google Analytics Debugger [extension](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna)




Upon going to localhost:8080.
1. It redirects immediately to localhost:8080/results due to this [line](https://github.com/web-platform-tests/wpt.fyi/blob/main/webapp/test_results_handler.go#L63) and the first google analytics event has fired
  - ![image](https://user-images.githubusercontent.com/7788930/189945167-72fdf229-c3fb-46ce-b34b-1b1824982453.png)
  - A blank page renders
  - ![image](https://user-images.githubusercontent.com/7788930/189945405-77efa191-2024-423d-b43b-4b5f51769486.png)
  - But the page's header contains the google analytics configuration which allows it to trigger.
2.  The break point triggeres a bunch of times
  - view=subtest is added first
  - view=subtest is removed then ?label=experimental&label=master&aligned is added
 3. When the page finally finishes rendering, it sends the second event with the query string parameters
 
</details>
